### ISSUE TITLE
Does not compile in iOS

### ISSUE THREAD

**Issue by jet082** [libretro/libretro-chailove#378]
This is related to this problem https://github.com/libretro/Dinothawr/issues/16#issuecomment-527801826

The solution is posted in a comment on this issue.

Error below:
```
<inline asm>:3:3: fatal error: unknown directive
  .arm
  ^
1 error generated.
make: *** [vendor/libretro-common/audio/conversion/float_to_s16_neon.o] Error 1
```

**Comment by RobLoach** [comment]
Thanks for the heads up! That .arm directive issue has plagued me for so long. Wish we could port it to C or somethign.

**Comment by jet082** [comment]
Well, I fixed it in Dinothawr. I actually ran it earlier today on my iPad Pro to confirm that it works fine in ARM64.

It would seem to be fixable here as well.

As per here.

![IMG_0011](https://user-images.githubusercontent.com/46708077/64419324-9fdb3480-d0d7-11e9-9c80-bd970d8ceebb.PNG)

**Comment by jet082** [comment]
Welp, I got chailove to compile on iOS arm64. It's my most complex iOS-arm64 compile yet, but it fundamentally just follows the same rules as my dinothawr fix (that is to say, to ignore the neon optimizations in the audio stuff - which is fine performance-wise). It's a bit more complex, as you need to also comment out stuff that won't be used (cd drive detection, etc). Instructions below.

First, run ``libretro-build-ios-arm64.sh chailove`` - it will fail, but this is fine. It needs to fetch some stuff and this is an easy way to do that.

Then make the following changes:

``Makefile`` - Remove the following lines (or comment them out)

```
rm -f $(TARGET) $(OBJECTS)
git clean -xdf
rm -rf vendor
git reset --hard HEAD
git submodule update -f --init --recursive
git submodule foreach --recursive git clean -xfd
git submodule foreach --recursive git reset --hard HEAD
35a43
@git submodule update --init --recursive
37a46
@git submodule update --remote
```

``Makefile.libretro`` - Make the following changes

```
CC = cc -arch arm64 -isysroot $(IOSSDK)

to

CC = cc -DDONT_WANT_ARM_OPTIMIZATIONS -arch arm64 -isysroot -DHAVE_POSIX_MEMALIGN $(IOSSDK)
HAVE_NEON = 0

CC +=  -miphoneos-version-min=8.0
CFLAGS += -miphoneos-version-min=8.0

to

CC +=  -miphoneos-version-min=8.0 -DHAVE_POSIX_MEMALIGN
CFLAGS += -miphoneos-version-min=8.0 -DHAVE_POSIX_MEMALIGN
```

``libretro-chailove/vendor/didstopia-physfs/src/physfs.c`` - Comment out the following lines

```
return doEnumStringList(__PHYSFS_platformDetectAvailableCDs);

__PHYSFS_platformDetectAvailableCDs(callback, data);
```

``libretro-chailove/vendor/didstopia-physfs/src/physfs.c``

```
if (!__PHYSFS_platformInit())

to

if (1 == 1)
```

``libretro-chailove/vendor/libretro-common/audio/conversion/float_to_s16.c`` - Comment out

```
void convert_float_s16_asm(int16_t *out, const float *in, size_t samples);

if (aligned_samples)
   convert_float_s16_asm(out, in, aligned_samples);
```

``libretro-chailove/vendor/libretro-common/audio/conversion/s16_to_float.c`` - Comment out

```
void convert_s16_float_asm(float *out, const int16_t *in,
      size_t samples, const float *gain);

if (aligned_samples)
   convert_s16_float_asm(out, in, aligned_samples, &gain);
```

Change ``#if defined(__ARM_NEON__)`` to ``#if defined(__ARM_NEON__) && false`` in ``libretro-chailove/vendor/libretro-common/audio/conversion/s16_to_float_neon.c``, ``libretro-chailove/vendor/libretro-common/audio/conversion/float_to_s16_neon.c``, and ``libretro-chailove/vendor/libretro-common/audio/resampler/drivers/sinc_resampler_neon.S``

``src/love/system.cpp`` - Comment out the following lines:

```
int result = std::system(command.c_str());
if (result != 0) {
	std::cout << "[ChaiLove] [system] Failed to execute " << command << std::endl;
	return false;
}
```

``vendor/libretro-common/audio/resampler/drivers/sinc_resampler.c`` - Comment out the following lines

```
void process_sinc_neon_asm(float *out, const float *left,
      const float *right, const float *coeff, unsigned taps);

process_sinc_neon_asm(output, buffer_l, buffer_r, phase_table, taps);
```

At this point, chailove will compile.

**Comment by jet082** [comment]
I had to update the comment above. The original edits compiled, but did not run. These do.

Evidence :D

![IMG_0019](https://user-images.githubusercontent.com/46708077/64478162-22025080-d1df-11e9-88de-0ed96b9f3bfa.PNG)

**Comment by WeedyWeedSmoker** [comment]
@jet082 On the latest non-beta Xcode, the instructions right here still fail...

I'll try again (along with easyrpg, BTW) when the Xcode 11 beta is installed, just waiting for the download to finish first... 😄

**Comment by WeedyWeedSmoker** [comment]
@jet082 Still no luck on the latest Xcode, failing with the exact same error with current instructions...

**Comment by RobLoach** [comment]
@WeedyWeedSmoker @jet082 Made a PR over at https://github.com/libretro/libretro-chailove/pull/380 .... Probably missed soemthing.

**Comment by jet082** [comment]
Fixed by https://github.com/libretro/libretro-chailove/commit/10d64cc67f51514cefbc264a52aa5d16c616d4c1
